package error_common

const (
	ERR_UNKNOWN                      = "ERR_UNKNOWN"
	ERR_NOTFOUND                     = "ERR_NOTFOUND"
	ERR_VALIDATE                     = "ERR_VALIDATE"
	ERR_INVALID_EMAIL                = "ERR_INVALID_EMAIL"
	ERR_INVALID_PHONE_NUMBER         = "ERR_INVALID_PHONE_NUMBER"
	ERR_INVALID_CREDENCIAS           = "ERR_INVALID_CREDENCIAS"
	ERR_EXISTING_EMAIL               = "ERR_EXISTING_EMAIL"
	ERR_EXISTING_PHONENUMBER         = "ERR_EXISTING_PHONENUMBER"
	ERR_GOOGLE_STORAGE_UNKNOWN       = "ERR_GOOGLE_STORAGE_UNKNOWN"
	ERR_CONFIGURATION_FILE_NOT_FOUND = "ERR_CONFIGURATION_FILE_NOT_FOUND"
	ERR_EXISTING_NATIONAL_REGISTRY   = "ERR_EXISTING_NATIONAL_REGISTRY"
	ERR_USER_NOTFOUND                = "ERR_USER_NOTFOUND"
)
